### ISSUE TITLE
github action that can deliver to the end users clusters based on a configuration file

### ISSUE THREAD

**Issue by jarededwards** [konstructio/kubefirst-api#559]
```
# example yaml, not final or necesary but the essence
clusters:
  - name: development
    namespaces:
      - development
      - ryans-development
  - name: staging
    namespaces:
      - staging
```
